/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Conexao;
import classes.Produto;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Etec
 */
public class telaProduto extends javax.swing.JFrame {


    public telaProduto() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Produto us;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcod = new javax.swing.JLabel();
        inputcod = new javax.swing.JTextField();
        lbimg = new javax.swing.JLabel();
        lbprod = new javax.swing.JLabel();
        inputprod = new javax.swing.JTextField();
        lbpreco = new javax.swing.JLabel();
        inputpreco = new javax.swing.JTextField();
        lbquant = new javax.swing.JLabel();
        inputquant = new javax.swing.JTextField();
        buttescolher = new javax.swing.JButton();
        buttsalvar = new javax.swing.JButton();
        butteditar = new javax.swing.JButton();
        buttexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbcod.setText("Codigo:");
        getContentPane().add(lbcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, 30));
        getContentPane().add(inputcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, 30));
        getContentPane().add(lbimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 110, 80));

        lbprod.setText("Produto:");
        getContentPane().add(lbprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 30));
        getContentPane().add(inputprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, 30));

        lbpreco.setText("Preço:");
        getContentPane().add(lbpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 30));
        getContentPane().add(inputpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, 30));

        lbquant.setText("Quantidade:");
        getContentPane().add(lbquant, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 70, 30));
        getContentPane().add(inputquant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, 30));

        buttescolher.setText("Escolher");
        buttescolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttescolherActionPerformed(evt);
            }
        });
        getContentPane().add(buttescolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 100, 30));

        buttsalvar.setText("Salvar");
        buttsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(buttsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 100, 30));

        butteditar.setText("Editar");
        butteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butteditarActionPerformed(evt);
            }
        });
        getContentPane().add(butteditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 100, 30));

        buttexcluir.setText("Excluir");
        buttexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(buttexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttsalvarActionPerformed
us= new Produto();
us.setCod(Integer.parseInt(inputcod.getText()));
us.setNomeprod(inputprod.getText());
us.setPreco(Double.parseDouble(inputpreco.getText()));
us.setQuant(Integer.parseInt(inputquant.getText()));
if(us.Salvar()!=0){
JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
}else{
JOptionPane.showMessageDialog(null, "Erro ao cadastrar");
} 
    }//GEN-LAST:event_buttsalvarActionPerformed

    private void butteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butteditarActionPerformed
us= new Produto();
us.setCod(Integer.parseInt(inputcod.getText()));
us.setNomeprod(inputprod.getText());
us.setPreco(Double.parseDouble(inputpreco.getText()));
us.setQuant(Integer.parseInt(inputquant.getText()));
if(us.Atualizar()==1){
JOptionPane.showMessageDialog(null, "Atualizado com sucesso");

}else{
JOptionPane.showMessageDialog(null, "Não foi possivel atualizar");
}

    }//GEN-LAST:event_butteditarActionPerformed

    private void buttexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttexcluirActionPerformed
 us= new Produto();
us.setCod(Integer.parseInt(inputcod.getText()));
us.setNomeprod(inputprod.getText());
us.setPreco(Double.parseDouble(inputpreco.getText()));
us.setQuant(Integer.parseInt(inputquant.getText()));
if(us.Excluir()==1){
JOptionPane.showMessageDialog(null, "Excluido com sucesso");
}else{
JOptionPane.showMessageDialog(null, "Excluido com inssucesso");

}  
    }//GEN-LAST:event_buttexcluirActionPerformed

    private void buttescolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttescolherActionPerformed
        String nome;
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".IMAGE", "jpg", "gif", "png");
        file.addChoosableFileFilter(filtro);
        int resultado = file.showOpenDialog(null);
        
        if(resultado == JFileChooser.APPROVE_OPTION){
            File selecionado = file.getSelectedFile();
            String caminho = selecionado.getAbsolutePath();
            lbimg.setIcon(carregaImagem(caminho));
            nome = caminho;        
        }                                           

        try
        {
            FileInputStream fis = new FileInputStream(arquivo);
            
    Conexao conexaoBD = new Conexao(); // Cria instância
    conexaoBD.Conectar();
        
            String sql = "INSERT INTO tb01_receitas (tb01_nome, tb01_descricao, tb01_foto) values (?,?,?)";
        
            PreparedStatement ps = (PreparedStatement) objetoBD.conexao.prepareStatement(sql);
           
            ps.setString(1, cbReceita.getSelectedItem().toString());           
            ps.setString(2, txReceita.getText().toString());
            ps.setBinaryStream(3, fis, (int) arquivo.length());
             
            int qtdreg = ps.executeUpdate();
            
             if (qtdreg == 0) {
                JOptionPane.showMessageDialog(null, "Receita já cadastrado");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Receita Incluida");
            }  
            objetoBD.desconectar();                        
        }
            catch (Exception e)
        {
           System.out.println(e.getMessage());

        }    
    }//GEN-LAST:event_buttescolherActionPerformed
private ImageIcon carregaImagem(String path){
        ImageIcon img = new ImageIcon(path);
        Image imag = img.getImage();
        Image minhimagem = imag.getScaledInstance(lbimg.getWidth(), lbimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imagem = new ImageIcon(minhimagem);
        return imagem;
    }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butteditar;
    private javax.swing.JButton buttescolher;
    private javax.swing.JButton buttexcluir;
    private javax.swing.JButton buttsalvar;
    private javax.swing.JTextField inputcod;
    private javax.swing.JTextField inputpreco;
    private javax.swing.JTextField inputprod;
    private javax.swing.JTextField inputquant;
    private javax.swing.JLabel lbcod;
    private javax.swing.JLabel lbimg;
    private javax.swing.JLabel lbpreco;
    private javax.swing.JLabel lbprod;
    private javax.swing.JLabel lbquant;
    // End of variables declaration//GEN-END:variables
}
