/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;
import classes.Matricula;
import classes.Usuario;
import classes.Aluno;
import classes.Turma;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Etec
 */
public class telaMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaMatricula
     */
    public telaMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Matricula us;

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combTurma = new javax.swing.JComboBox();
        combRM = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnmatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsituacao = new javax.swing.JTextField();
        txtanolet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        combTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combTurmaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("RM");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Turma");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nº da Matricula");

        txtnmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmatriculaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Situação");

        txtsituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsituacaoActionPerformed(evt);
            }
        });

        txtanolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanoletActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ano Letivo");

        btnSal.setBackground(new java.awt.Color(255, 0, 0));
        btnSal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSal.setText("Salvar");
        btnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("MATRÍCULA");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° da Mat", "Turma", "RM", "Situação", "Ano Letivo"
            }
        ));
        jScrollPane1.setViewportView(tblDados);

        btnExcluir.setBackground(new java.awt.Color(255, 51, 51));
        btnExcluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisa.setBackground(new java.awt.Color(255, 51, 51));
        btnPesquisa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 51, 51));
        btnEditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsituacao)
                                    .addComponent(combRM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnmatricula)
                                    .addComponent(txtanolet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditar)
                        .addGap(28, 28, 28)
                        .addComponent(btnSal)
                        .addGap(28, 28, 28)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtanolet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSal)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmatriculaActionPerformed

    private void txtsituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsituacaoActionPerformed

    private void btnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalActionPerformed
us= new Matricula();
Turma t = new Turma();
t = (Turma) combTurma.getSelectedItem();
us.setTurma(t.getCod());
us.setRm(combRM.getSelectedItem().toString());
us.setNmat(txtnmatricula.getText());
us.setSituacao(txtsituacao.getText());
us.setAno(txtanolet.getText());
if(us.Salvar()!=0){
JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
}else{
JOptionPane.showMessageDialog(null, "Erro ao cadastrar");

}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalActionPerformed

    private void txtanoletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanoletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanoletActionPerformed

    private void combTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combTurmaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Turma t = new Turma("","");
        ResultSet ka = t.carregar3();
        combTurma.addItem(new Turma("", "Selecione a turma"));
        try {
            while(ka.next()){
                combTurma.addItem(new Turma(ka.getString("tb02_cod_turma"),
                                            ka.getString("tb02_nome")));
            }
            ka.close();
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
        Aluno a = new Aluno(0,"");
        ResultSet rs = a.carregar2();
        combRM.addItem(new Aluno(0, "Selecione o rm"));
        try {
            while(rs.next()){
               combRM.addItem(new Aluno(rs.getInt("tb03_rm"),
               rs.getString("tb03_nome")));
                                            
            }
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
        
        DefaultTableModel tab = (DefaultTableModel) tblDados.getModel();
        us= new Matricula();
        rs=null;
        rs = us.PesquisarTodos();
        try{
        while (rs.next()){
        tab.addRow(new Object[]{rs.getString("tb04_num"), rs.getString("tb04_cod_turma"), rs.getString("tb04_rm"), rs.getString("tb04_situação"), rs.getString("tb04_ano_letivo")});
        }
        tblDados.setModel(tab);
        }catch (SQLException ex){
        System.out.println("Erro:" +ex);
    } 
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        us = new Matricula();
        us.setNmat(txtnmatricula.getText());
        if(us.Excluir()==1){
            JOptionPane.showMessageDialog(null, "Excluido com sucesso");
        }else{
            JOptionPane.showMessageDialog(null, "Excluido com inssucesso");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        us= new Matricula();
        ResultSet rs= null;
        us.setNmat(txtnmatricula.getText());
        rs = us.PesquisarId();
        
        try {
            if(rs.next()){
                txtanolet.setText(rs.getString("tb04_ano_letivo"));
                txtsituacao.setText(rs.getString("tb04_situação"));
                combTurma.setSelectedItem(rs.getString("tb04_cod_turma"));
                combRM.setSelectedItem(rs.getString("tb04_rm"));

            }else{
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar");

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(telasUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        us = new Matricula();
        us.setNmat(txtnmatricula.getText());
        us.setAno(txtanolet.getText());
        us.setSituacao(txtsituacao.getText());
        if(us.Atualizar()==1){
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso");

        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel atualizar");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSal;
    private javax.swing.JComboBox combRM;
    private javax.swing.JComboBox combTurma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtanolet;
    private javax.swing.JTextField txtnmatricula;
    private javax.swing.JTextField txtsituacao;
    // End of variables declaration//GEN-END:variables
}
