/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import classVo.classC;
import classVo.classM;
import classVo.classP;
import javax.swing.JOptionPane;

/**
 *
 * @author Etec
 */
public class TelaMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaMedico
     */
    public TelaMedico() {
        initComponents();
    }
   classM[] vetmed = new classM[5];
   classP[] vetpac = new classP[5];
   classC[] vetcon  = new classC[5];
   int imed=0, ipac=0, icon=0;
   
   public void passavetor(classM[]m, classP[]p, classC[] c, int  im, int ip,int ic ){
       vetmed = m;
       vetpac = p;
       vetcon = c;
       imed = im;
       ipac = ip;
       icon = ic;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcrm = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtespecialidade = new javax.swing.JTextField();
        butprincipal = new javax.swing.JToggleButton();
        butcadastro = new javax.swing.JToggleButton();
        butmostrar = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tela Medico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, -1));

        jLabel2.setText("CRM:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 130, 40, -1));

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setText("Especialiade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 210, 80, -1));
        getContentPane().add(txtcrm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 200, -1));
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, -1));
        getContentPane().add(txtespecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 200, -1));

        butprincipal.setBackground(new java.awt.Color(132, 132, 132));
        butprincipal.setText("Tela Principal");
        butprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butprincipalActionPerformed(evt);
            }
        });
        getContentPane().add(butprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        butcadastro.setBackground(new java.awt.Color(132, 132, 132));
        butcadastro.setText("Cadastrar");
        butcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcadastroActionPerformed(evt);
            }
        });
        getContentPane().add(butcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        butmostrar.setBackground(new java.awt.Color(132, 132, 132));
        butmostrar.setText("Mostrar");
        butmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(butmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butprincipalActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.retorna(vetmed, vetpac, vetcon, imed, ipac, ipac);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);   
        this.dispose();
    }//GEN-LAST:event_butprincipalActionPerformed

    private void butcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcadastroActionPerformed
    if(imed<5){
    classM alguem = new classM();
    alguem.setCRM(txtcrm.getText());
    alguem.setNome(txtnome.getText());
    alguem.setEspecialidade(txtespecialidade.getText());
    vetmed[imed]= alguem;
    imed++;
    }
    else{
        JOptionPane.showMessageDialog(null,"nao é possivel cadastrar");
    }
    
    limpar();
    }//GEN-LAST:event_butcadastroActionPerformed

    private void butmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butmostrarActionPerformed
     String texto = "";
     for (int i=0;i<imed; i++){
         texto+="nome="+vetmed[i].getNome()+"- CRM="+ vetmed[i].getCRM()+
                 "- Especialidade="+vetmed[i].getEspecialidade()+"\n";
     }
     JOptionPane.showMessageDialog(null,texto);
    }//GEN-LAST:event_butmostrarActionPerformed
private void limpar(){
    txtnome.setText(null);
    txtcrm.setText(null);
    txtespecialidade.setText(null);
}
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butcadastro;
    private javax.swing.JToggleButton butmostrar;
    private javax.swing.JToggleButton butprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcrm;
    private javax.swing.JTextField txtespecialidade;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
