/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import classVo.classC;
import classVo.classM;
import classVo.classP;
import javax.swing.JOptionPane;

/**
 *
 * @author Etec
 */
public class TelaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsulta
     */
    public TelaConsulta() {
        initComponents();
    }
   classM[] vetmed = new classM[5];
   classP[] vetpac = new classP[5];
   classC[] vetcon  = new classC[5];
   int imed=0, ipac=0, icon=0, x=0;
   
   public void passavetor(classM[]m, classP[]p, classC[] c, int  im, int ip,int ic ){
       vetmed = m;
       vetpac = p;
       vetcon = c;
       imed = im;
       ipac = ip;
       icon = ic;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        smedicos = new javax.swing.JComboBox<>();
        spaciente = new javax.swing.JComboBox<>();
        txtvalor = new javax.swing.JTextField();
        butcadastro = new javax.swing.JToggleButton();
        butmostrar = new javax.swing.JToggleButton();
        butprincipal = new javax.swing.JToggleButton();
        txtdata = new javax.swing.JFormattedTextField();
        txthora = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tela Consulta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel2.setText("Medico:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel3.setText("Paciente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel4.setText("Data:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 40, 20));

        jLabel5.setText("Horario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 20));

        jLabel6.setText("Valor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        getContentPane().add(smedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 290, -1));

        getContentPane().add(spaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 290, -1));
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 290, -1));

        butcadastro.setBackground(new java.awt.Color(132, 132, 132));
        butcadastro.setText("Cadastrar");
        butcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcadastroActionPerformed(evt);
            }
        });
        getContentPane().add(butcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        butmostrar.setBackground(new java.awt.Color(132, 132, 132));
        butmostrar.setText("Mostrar");
        butmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(butmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        butprincipal.setBackground(new java.awt.Color(132, 132, 132));
        butprincipal.setText("Tela Principal");
        butprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butprincipalActionPerformed(evt);
            }
        });
        getContentPane().add(butprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, -1));

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 290, -1));

        try {
            txthora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 290, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butprincipalActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.retorna(vetmed, vetpac, vetcon, imed, ipac, ipac);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butprincipalActionPerformed

    private void butcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcadastroActionPerformed
     if (smedicos.getSelectedItem().toString().isEmpty() || spaciente.getSelectedItem().toString().isEmpty()
          || txtdata.getText().isEmpty() || txthora.getText().isEmpty() ||txtvalor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "preencha todos os campos!");
        }
        
        if (x<5 && !smedicos.getSelectedItem().toString().isEmpty() && !spaciente.getSelectedItem().toString().isEmpty()
        && !txtdata.getText().isEmpty() && !txthora.getText().isEmpty() && !txtvalor.getText().isEmpty()){
    classC alguem = new classC();
    alguem.setMedico(smedicos.getSelectedItem().toString());
    alguem.setPaciente(spaciente.getSelectedItem().toString());
    alguem.setDt(txtdata.getText());
    alguem.setHorario(txthora.getText());
    alguem.setValor(txtvalor.getText());
       vetcon[x]= alguem;
    x++;
    }
    else{
        JOptionPane.showMessageDialog(null,"nao é possivel cadastrar");
    }
    limpar();
    }//GEN-LAST:event_butcadastroActionPerformed

    private void butmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butmostrarActionPerformed
 String texto = "";
        for (int i=0; i<x; i++){
            texto+="Medico = "+vetcon[i].getMedico() + "  -  Paciente = " + vetcon[i].getPaciente() +
            "  -  Data = " + vetcon[i].getDt() + "  -  Horario = " + vetcon[i].getHorario() + "  -  Valor = " + vetcon[i].getValor() + "\n";
     }
     JOptionPane.showMessageDialog(null,texto);
    }//GEN-LAST:event_butmostrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (int i = 0;i<imed;i++){
            smedicos.addItem(vetmed[i].getNome());
        }
        for (int i = 0;i<ipac;i++){
            spaciente.addItem(vetpac[i].getNome());
        }
    }//GEN-LAST:event_formWindowOpened
private void limpar(){
    txthora.setText(null);
    txtvalor.setText(null);
    txtdata.setText(null);
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butcadastro;
    private javax.swing.JToggleButton butmostrar;
    private javax.swing.JToggleButton butprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> smedicos;
    private javax.swing.JComboBox<String> spaciente;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JFormattedTextField txthora;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
