/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

/**
 *
 * @author Etec
 */
public class Tmenu extends javax.swing.JFrame {

    /**
     * Creates new form Tmenu
     */
    public Tmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButAg = new javax.swing.JToggleButton();
        ButPet = new javax.swing.JToggleButton();
        ButP = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButAg.setText("botão agendamento");
        ButAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAgActionPerformed(evt);
            }
        });
        getContentPane().add(ButAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 50, -1, -1));

        ButPet.setText("botão pet");
        ButPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPetActionPerformed(evt);
            }
        });
        getContentPane().add(ButPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        ButP.setText("botão pessoa");
        ButP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPActionPerformed(evt);
            }
        });
        getContentPane().add(ButP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAgActionPerformed
        TelaAg tela = new TelaAg();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButAgActionPerformed

    private void ButPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPetActionPerformed
        TelaP tela = new TelaP();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButPetActionPerformed

    private void ButPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPActionPerformed
        TelaPessoa tela = new TelaPessoa();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButAg;
    private javax.swing.JToggleButton ButP;
    private javax.swing.JToggleButton ButPet;
    // End of variables declaration//GEN-END:variables
}
