/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Conexao;
import static Classes.Conexao.statement;
import Classes.corrida;
import java.awt.Font;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Element;
import static javax.swing.text.StyleConstants.FontFamily;
import org.w3c.dom.Document;

/**
 *
 * @author etec
 */
public class telacorrida extends javax.swing.JFrame {

    /**
     * Creates new form telacorrida
     */
    public telacorrida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    corrida us;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbimg1 = new javax.swing.JLabel();
        lbimg3 = new javax.swing.JLabel();
        lbimg4 = new javax.swing.JLabel();
        lbimg2 = new javax.swing.JLabel();
        imgprincipal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdados = new javax.swing.JTable();
        txtpesq = new javax.swing.JTextField();
        buttonpesq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgcima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbimg1.setText("jLabel4");
        lbimg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbimg1MouseClicked(evt);
            }
        });
        jPanel1.add(lbimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, 50));

        lbimg3.setText("jLabel4");
        lbimg3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbimg3MouseClicked(evt);
            }
        });
        jPanel1.add(lbimg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 50));

        lbimg4.setText("jLabel4");
        jPanel1.add(lbimg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 60, 50));

        lbimg2.setText("jLabel4");
        jPanel1.add(lbimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 60, 50));

        imgprincipal.setText("jLabel4");
        jPanel1.add(imgprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 440));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbdados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbdados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Peso", "Altura", "Sexo", "Email", "inscricao"
            }
        ));
        tbdados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdados);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 470, 240));

        txtpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqActionPerformed(evt);
            }
        });
        jPanel2.add(txtpesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, -1));

        buttonpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpesqActionPerformed(evt);
            }
        });
        jPanel2.add(buttonpesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 30, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Corrida De Rua");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 30));

        jLabel2.setForeground(new java.awt.Color(51, 255, 102));
        jLabel2.setText("A Correria Saudavel!!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 120, -1));

        imgcima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        jPanel2.add(imgcima, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqActionPerformed
        
    }//GEN-LAST:event_txtpesqActionPerformed

    private void buttonpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpesqActionPerformed
    DefaultTableModel dm = (DefaultTableModel)tbdados.getModel();
while(dm.getRowCount() > 0)
{
    dm.removeRow(0);
}

        
        DefaultTableModel tab = (DefaultTableModel) tbdados.getModel();
us= new corrida();
ResultSet rs= null;
us.setNome(String.valueOf(txtpesq.getText()));
rs = us.PesquisarTodos();
try{
while (rs.next()){
tab.addRow(new Object[]{rs.getString("tb01_nome"), rs.getDouble("tb01_peso"), rs.getDouble("tb01_altura"), rs.getString("tb01_sexo"), rs.getString("tb01_email"), rs.getInt("tb01_inscricao")});
}
tbdados.setModel(tab);
}catch (SQLException ex){
    System.out.println("Erro:" +ex);
    }
    }//GEN-LAST:event_buttonpesqActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
ImageIcon imagem5 = new  ImageIcon(corrida.class.getResource("/imagens/imagem corrida.png"));
        
Image imag5 = imagem5.getImage().getScaledInstance(imgprincipal.getWidth(), imgprincipal.getHeight(), Image.SCALE_DEFAULT);
        
imgprincipal.setIcon(new ImageIcon(imag5));

ImageIcon imagem = new  ImageIcon(corrida.class.getResource("/imagens/pdf.png"));
        
Image imag = imagem.getImage().getScaledInstance(lbimg1.getWidth(), lbimg1.getHeight(), Image.SCALE_DEFAULT);
        
lbimg1.setIcon(new ImageIcon(imag));

ImageIcon imagem2 = new  ImageIcon(corrida.class.getResource("/imagens/1032.png"));
        
Image imag2 = imagem2.getImage().getScaledInstance(lbimg2.getWidth(), lbimg2.getHeight(), Image.SCALE_DEFAULT);
        
lbimg2.setIcon(new ImageIcon(imag2));

ImageIcon imagem3 = new  ImageIcon(corrida.class.getResource("/imagens/boleto.png"));
        
Image imag3 = imagem3.getImage().getScaledInstance(lbimg3.getWidth(), lbimg3.getHeight(), Image.SCALE_DEFAULT);
        
lbimg3.setIcon(new ImageIcon(imag3));

ImageIcon imagem4 = new  ImageIcon(corrida.class.getResource("/imagens/email.png"));
        
Image imag4 = imagem4.getImage().getScaledInstance(lbimg4.getWidth(), lbimg4.getHeight(), Image.SCALE_DEFAULT);
        
lbimg4.setIcon(new ImageIcon(imag4));

DefaultTableModel tab = (DefaultTableModel) tbdados.getModel();
us= new corrida();
ResultSet rs= null;
us.setNome(String.valueOf(txtpesq.getText()));
rs = us.PesquisarTodos2();
try{
while (rs.next()){
tab.addRow(new Object[]{rs.getString("tb01_nome"), rs.getDouble("tb01_peso"), rs.getDouble("tb01_altura"), rs.getString("tb01_sexo"), rs.getString("tb01_email"), rs.getInt("tb01_inscricao")});
}
tbdados.setModel(tab);
}catch (SQLException ex){
    System.out.println("Erro:" +ex);
    }

    }//GEN-LAST:event_formWindowOpened

    private void lbimg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbimg1MouseClicked
        
    }//GEN-LAST:event_lbimg1MouseClicked

    private void lbimg3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbimg3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbimg3MouseClicked

    private void tbdadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdadosMouseClicked
    try {     
            Conexao objetoBD = new Conexao();
        String sql = "SELECT * FROM tb01_corrida WHERE tb01_nome = '" + txtpesq.getText() + "'";
        objetoBD.Conectar();
       
        ResultSet rs = statement.executeQuery(sql);
        
        if (!rs.next())
        {
           JOptionPane.showMessageDialog(null, "Consulta Invalida");        
           return;
        }
        else
            {
            Image img = Toolkit.getDefaultToolkit().createImage(rs.getBytes("tb01_imagem"));
            ImageIcon foto = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(93, 126, Image.SCALE_DEFAULT));
            imgcima.setIcon(foto); 
            }
        
        objetoBD.desconectar();
        statement.close(); 
        }
               
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        }     

    
    }//GEN-LAST:event_tbdadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telacorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telacorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telacorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telacorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telacorrida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonpesq;
    private javax.swing.JLabel imgcima;
    private javax.swing.JLabel imgprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbimg1;
    private javax.swing.JLabel lbimg2;
    private javax.swing.JLabel lbimg3;
    private javax.swing.JLabel lbimg4;
    private javax.swing.JTable tbdados;
    private javax.swing.JTextField txtpesq;
    // End of variables declaration//GEN-END:variables
}
