/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import tela.Tela;
import java.awt.Image;
import java.math.BigDecimal;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Aluno
 */
public class Tela extends javax.swing.JFrame {
 
   
    double pre[] = {15.00,7.25,2.50,10.00,3.00,9.00,3.60,12.40,14.20}; 
    JLabel[] tot; 
    double tr;
    JLabel salga[] = new JLabel[10];
    int n;
     String im[] = {"/imagem/red.jfif","/imagem/top.jpg","/imagem/ed+.png","/imagem/flinck.jfif","/imagem/sucri.jfif","/imagem/treeps.jfif","/imagem/micos.jpeg", "/imagem/beijaF.jpg", "/imagem/lobits.jpg"};
     int soma;
     int testa=0;
     int cont1;
   
 

    
    public Tela() {
        initComponents();
        
          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        produto = new javax.swing.JLabel();
        vis = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        troco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img1.setBackground(new java.awt.Color(255, 255, 255));
        img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img1MouseClicked(evt);
            }
        });
        jPanel1.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img2MouseClicked(evt);
            }
        });
        jPanel1.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 60));

        img3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img3MouseClicked(evt);
            }
        });
        jPanel1.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 70, 60));

        img4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 60));

        img5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 60));

        img6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 70, 60));

        img7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 60));

        img8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 60));

        img9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, 60));

        p1.setText("2.50");
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 30, -1));

        p2.setText("7.25");
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 30, -1));

        p3.setText("15.00");
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        p4.setText("10.00");
        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        p5.setText("3.00");
        jPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        p6.setText("9.00");
        jPanel1.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        p7.setText("3.60");
        jPanel1.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        p8.setText("12.40");
        jPanel1.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        p9.setText("14.20");
        jPanel1.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 270));

        produto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoMouseClicked(evt);
            }
        });
        getContentPane().add(produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 80, 80));

        vis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vis.setText("0");
        vis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(vis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, 30));

        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 60, 50));

        r2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 60, 50));

        r3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r3MouseClicked(evt);
            }
        });
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, 50));

        bt7.setBackground(new java.awt.Color(0, 0, 0));
        bt7.setForeground(new java.awt.Color(255, 255, 255));
        bt7.setText("7");
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt7MouseClicked(evt);
            }
        });
        getContentPane().add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 50, 50));

        bt8.setBackground(new java.awt.Color(0, 0, 0));
        bt8.setForeground(new java.awt.Color(255, 255, 255));
        bt8.setText("8");
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt8MouseClicked(evt);
            }
        });
        getContentPane().add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 50, 50));

        bt4.setBackground(new java.awt.Color(0, 0, 0));
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("4");
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt4MouseClicked(evt);
            }
        });
        getContentPane().add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 50));

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("1");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt1MouseClicked(evt);
            }
        });
        getContentPane().add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 50, 50));

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("2");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt2MouseClicked(evt);
            }
        });
        getContentPane().add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 50, 50));

        bt3.setBackground(new java.awt.Color(0, 0, 0));
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("3");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt3MouseClicked(evt);
            }
        });
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 50, 50));

        bt6.setBackground(new java.awt.Color(0, 0, 0));
        bt6.setForeground(new java.awt.Color(255, 255, 255));
        bt6.setText("6");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt6MouseClicked(evt);
            }
        });
        getContentPane().add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 50, 50));

        bt9.setBackground(new java.awt.Color(0, 0, 0));
        bt9.setForeground(new java.awt.Color(255, 255, 255));
        bt9.setText("9");
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt9MouseClicked(evt);
            }
        });
        getContentPane().add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 50, 50));

        bt5.setBackground(new java.awt.Color(0, 0, 0));
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("5");
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt5MouseClicked(evt);
            }
        });
        getContentPane().add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 50, 50));

        troco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        troco.setText("0");
        troco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        troco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trocoMouseClicked(evt);
            }
        });
        getContentPane().add(troco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
    graninha(2);
  
    }//GEN-LAST:event_r1MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
    graninha(5);
    }//GEN-LAST:event_r2MouseClicked

    private void r3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r3MouseClicked
    graninha(10);
    }//GEN-LAST:event_r3MouseClicked

    private void img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MouseClicked
    
    }//GEN-LAST:event_img1MouseClicked

    private void img2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MouseClicked
        
    }//GEN-LAST:event_img2MouseClicked

    private void img3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img3MouseClicked
        
    }//GEN-LAST:event_img3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon imagem;
//       
        imagem = new ImageIcon(this.getClass().getResource("/imagem/10real.jpg"));
        Image imag4 = imagem.getImage().getScaledInstance(r3.getWidth(),
         r3.getHeight(),  Image.SCALE_DEFAULT);
        r3.setIcon(new ImageIcon( imag4));
        
        imagem = new ImageIcon(this.getClass().getResource("/imagem/5real.jpg"));
        Image imag5 = imagem.getImage().getScaledInstance(r2.getWidth(),
         r2.getHeight(),  Image.SCALE_DEFAULT);
        r2.setIcon(new ImageIcon( imag5));
        imagem = new ImageIcon(this.getClass().getResource("/imagem/2real.png"));
        Image imag6 = imagem.getImage().getScaledInstance(r1.getWidth(),
         r1.getHeight(),  Image.SCALE_DEFAULT);
        r1.setIcon(new ImageIcon( imag6));
        salga[0]=img1;
        salga[1]=img2;
        salga[2]=img3;
        salga[3]=img4;
        salga[4]=img5;
        salga[5]=img6;
        salga[6]=img7;
        salga[7]=img8;
        salga[8]=img9;
        
        this.tetra();
        
        for( cont1=0; cont1<9; cont1++){
   
            imagem = new  ImageIcon(Tela.class.getResource(im[cont1]));
Image imag14 = imagem.getImage().getScaledInstance(salga[cont1].getWidth(), salga[cont1].getHeight(), Image.SCALE_DEFAULT);  
salga[cont1].setIcon(new ImageIcon(imag14));
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void bt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseClicked
       n=1;
       this.tetra();
      
    }//GEN-LAST:event_bt1MouseClicked

    private void bt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseClicked
       n=2;
       this.tetra();
      
    }//GEN-LAST:event_bt2MouseClicked

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
 
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseClicked
      n=3;
      this.tetra();

    }//GEN-LAST:event_bt3MouseClicked

    private void bt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseClicked
      n=4;
      this.tetra();

    }//GEN-LAST:event_bt4MouseClicked

    private void bt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseClicked
      n=5;
      this.tetra();

    }//GEN-LAST:event_bt5MouseClicked

    private void bt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseClicked
      n=6;
      this.tetra();

    }//GEN-LAST:event_bt6MouseClicked

    private void bt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseClicked
      n=7;
      this.tetra();
   
    }//GEN-LAST:event_bt7MouseClicked

    private void bt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseClicked
     n=8;
      this.tetra();
  
    }//GEN-LAST:event_bt8MouseClicked

    private void bt9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseClicked
      n=9;
      this.tetra();
 
    }//GEN-LAST:event_bt9MouseClicked

    private void trocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trocoMouseClicked

    }//GEN-LAST:event_trocoMouseClicked

    private void produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoMouseClicked
   this.dispose();
   Tela tela = new Tela();
   tela.setVisible(true);
        
    }//GEN-LAST:event_produtoMouseClicked
                           
    private void tetra(){
         
    for(int cont=0; cont<9; cont++){
         
        if(n-1==cont && soma>=(pre[cont])&& testa ==0){{
            
        testa=1; 
        
        this.movimento(salga[cont]);
         
    tr = soma - pre[cont];
     BigDecimal valor = new BigDecimal(tr);
       NumberFormat nf = NumberFormat.getCurrencyInstance();  
       String formatado = nf.format(tr);

    troco.setText(""+formatado);

        }     

    }
    }
    }
    
    private void graninha(int par){
        if(testa==0){
       soma = soma+par;
       BigDecimal valor = new BigDecimal(soma);
       NumberFormat nf = NumberFormat.getCurrencyInstance();  
       String formatado = nf.format(soma);
       vis.setText(""+formatado);
        }
    }
    
   public void movimento(final JLabel fig)
    {             
        new Thread()
        {
            public void run()
            { 
               int y = fig.getLocation().y;
               int x = fig.getLocation().x;
               int z = produto.getLocation().y;            
               
                while(y <= z)
                {
                    y = y + 1; 
                   fig.setLocation(x,y);
                    
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
                produto.setIcon(fig.getIcon());  
                fig.setIcon(null);
            }
            
        }.start();
    }
    
           
        
    
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

      
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    private javax.swing.JLabel produto;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel troco;
    private javax.swing.JLabel vis;
    // End of variables declaration//GEN-END:variables
}
